print('Find the square value')
print('---------------------')
a=65
print('square value is:',a**2)
print('')
print('Find square root')
print('----------------')
print('square root is',a**0.5)
print('')
print('Find cube')
print('----------')
print('cube  value is ',a**3)
print('')
print('find cuberoot')
print('---------------')
print('cube root value is',a**(1/3))
